### ISSUE TITLE
Detail Page

### ISSUE THREAD

**Issue by floodoo** [floodoo/untis_phasierung#16]
Auf der Detailpage sollen die Infos ordentlich angezeigt werden und nicht als Kurzfassung. Und die Phasenart.

**Comment by DevKevYT** [comment]
Ideen was alles in die Detail Page rein könnte:

* Wenn Ausfall oder Änderung, das ausschreiben als z.B. "Ausfall" oder bei änderung "Ersatz" und die ursprüngliche stunde (Mit Farbe) Dann weiß der User auch direkt was die Streifen am Rand einer Stunde bedeuten
* Phasierung aussschreiben. "Freie Phase" oder "Strukturierte Phase" (+ Erklärung?). Vielleicht können wir uns so sogar die Legende sparen. Ansonsten hinweisen wo und wie der Benutzer die Phasierung laden kann (Falls nicht geladen)
*  Wenn der Lehrer einen Text für die Stunde gesetzt hat anzeigen. Das geht mit ner neuen Funktion in `TimetableHour.getLessionInformation()` (in /lib/core/api/models/timetable.hour.dart)
