### ISSUE TITLE
Profilbild hinzufügen

### ISSUE THREAD

**Issue by floodoo** [floodoo/untis_phasierung#24]

**Comment by DevKevYT** [comment]
Ist gemacht. Ist aber schrecklich formatiert wäre cool wenn du nochmal drüber schauen könntest

**Comment by floodoo** [comment]
Formatiert und ins else gepackt. Username zu holden bringt nichts => Ich hab den User bereits durch das einloggen => Hole ich schon aus dem TimeTable Service

**Comment by floodoo** [comment]
Ich pack noch einen CircularProgressIndicator dazu während er lädt
