### ISSUE TITLE
Lightmode CircularProgressIndicator ist unsichtbar (weiß auf weiß)

### ISSUE THREAD

**Issue by DevKevYT** [floodoo/untis_phasierung#42]
Das ding was sich beim laden kreiselt keine Ahnung wie man das nenne HAHA
Das ist beim lightmode unsichtbar

**Comment by floodoo** [comment]
CircularProgressIndicator haha

**Comment by floodoo** [comment]
Wo ist es unsichtbar?

**Comment by DevKevYT** [comment]
Wenn man im lightmode ist und einen Stundenplan lädt
