### ISSUE TITLE
Manuelle Stundenplan aktualisierung

### ISSUE THREAD

**Issue by DevKevYT** [floodoo/untis_phasierung#56]
Durch cachen muss es möglich sein einen Stundenplan durch ziehen manuell neu laden zu können.

Dann muss nur die Funktion `UserSession.clearTimetableCache()` aufgerufen werden. und halt der derzeitige Stundenplan nochmal normal geladen werden

**Comment by floodoo** [comment]
Notiz an mich => Push to refresh
[https://pub.dev/packages/pull_to_refresh](https://pub.dev/packages/pull_to_refresh)
