### ISSUE TITLE
Login screen: Textfield clear bei Tastaturwechsel

### ISSUE THREAD

**Issue by DevKevYT** [floodoo/untis_phasierung#59]
Durch diesen Bug ist es nicht möglich sich einzuloggen.
Getestet auf realem Gerät.

Wenn man z.B. das Passwort eingeben will und dann bei der Tastatur auf den Button klickt wo man Symbole eingeben kann
löscht sich das Textfeld.

Allgemein haben die beiden Login Textfelder ein sehr seltsames verhalten:
Manchmal werden sie ganz gelöscht, manchmal taucht ein alter Text auf den man davor eingegeben hat ...

Edit: Das Textfeld wird auch beim schließen der Tastatur gelöscht

**Comment by floodoo** [comment]
Notiz an mich → Fehler gefunden muss nur noch umsetzten

Liegt am automatischen Login. Da User und Passwort da ist, versucht die App sich automatisch einzuloggen. Dies soll da natürlich nicht passieren. Dadurch wirft die App eine Exception und löscht die Daten.

**Comment by floodoo** [comment]
Und ja irgendwie verhalten die Textfelder sich komisch. Bei Textfeld wechsel ist zum Beispiel der Curser immer ganz links, obwohl Text drinne ist. Was verhält sich noch komisch? @DevKevYT
