### ISSUE TITLE
Null check Error beim Laden einer Phasierungs excel Datei

### ISSUE THREAD

**Issue by DevKevYT** [floodoo/untis_phasierung#61]
Titel
Bitte Stacktrace / Detaillierte Fehlermeldung wo der Fehler auftritt

**Comment by floodoo** [comment]
<img width="630" alt="Bildschirmfoto 2022-01-17 um 12 08 41" src="https://user-images.githubusercontent.com/59688267/149759181-c7e4d3c4-d09a-4049-85cb-280251fd8f42.png">

**Comment by floodoo** [comment]
lib/core/api/timetable.dart Zeile 223
