### ISSUE TITLE
Ein App Logo erstellen

### ISSUE THREAD

**Issue by DevKevYT** [floodoo/untis_phasierung#82]
Wir brauchen ein App-Icon. Kannst kreativ werden und dir selber was geiles überlegen

**Comment by Teshiification** [comment]
<h1>Iconidee-1 - Angelehnt an original Untis</h1>

_<p>Farbanordnung_ soll ein P für Phasierung darstellen.</p>

- Auflösung: 864 x 864 (Angeblich für Andorid zum automatischen downscaling am besten?)
- Format: .png

<details>
<summary>Blau</summary>

![Phasierung_Blau](https://user-images.githubusercontent.com/54819795/150326698-66a80b61-c6cb-4aea-bb41-2757305ca1a2.png)

</details>

<details>
<summary>Grün</summary>

![Phasierung_Gruen](https://user-images.githubusercontent.com/54819795/150326700-e2786230-4471-4f98-92eb-89cc2c30d32a.png)

</details>
<details>
<summary>Orange</summary>

![Phasierung_Orange](https://user-images.githubusercontent.com/54819795/150326705-d3d2b31e-5c1d-4e3a-a6a2-1dfdbefe4de2.png)

</details>

<details>
<summary>Bunt</summary>

![Phasierung_Bunt](https://user-images.githubusercontent.com/54819795/150326699-b1e52504-a350-4001-9da8-9e084641eca6.png)

</details>

**Comment by DevKevYT** [comment]
Perfekt! Ich finde das orange am besten. Wenn du willst kannst du das Bild in /assets/images/ reinpacken im main Branch dann bist du auch contributor
